### ISSUE TITLE
Investigate the effects of low topoquantization epsilon values

### ISSUE THREAD

**Issue by mattijn** [mattijn/topojson#110]
Given the following behaviour:
```python
import topojson as tp
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
tp.Topology(data=world).toposimplify(4).topoquantize(500).to_alt(color='properties.name:N')
```
![image](https://user-images.githubusercontent.com/5186265/90974953-2890f180-e530-11ea-9263-96a24f8b7137.png)

Are these artifacts explainable by the principles of `quantization` or is there a certain process that needs improvement?

Help is welcome!

**Comment by ljwolf** [comment]
We're seeing these issues as well.
![Screenshot_20201201_160248](https://user-images.githubusercontent.com/2250995/100765130-0f30f880-33ef-11eb-9e25-2eb64c261610.png)


[brexit.gpkg.zip](https://github.com/mattijn/topojson/files/5623828/brexit.gpkg.zip)

Interested in digging into this...

**Comment by mattijn** [comment]
Thanks for your interest in this issue. At this place in the docs https://mattijn.github.io/topojson/example/settings-tuning.html#prequantize I've worked out the quantization process in 1D.

I see you have linked this issue to another at the geopandas repo. Im still figuring out what is going wrong here. Maybe your usecase is a smaller reproducible example.

**Comment by mattijn** [comment]
Found a use-case small enough for debugging:
```python
import topojson as tp
import geopandas as gpd

gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
gdf = gdf[gdf.name.isin(['France', 'Belgium', 'Netherlands'])]
tp.Topology(data=gdf).toposimplify(4).topoquantize(500).to_alt(color='properties.name:N')
```
<img width="463" alt="image" src="https://user-images.githubusercontent.com/5186265/101944965-d7476380-3bed-11eb-94ed-30a6bf585296.png">

**Comment by mattijn** [comment]
Thanks again for commenting in order to bring this issue on my radar again!

This issue is fixed by #116, linestrings which can become points due filtering of repeating coordinates were not written back to the linestring. After delta-encoding the start-coordinates of quantised linestrings got mixed up with this case.

During debugging I found out that the overal bbox is not regenerated after simplification and quantization. Filled #117 for this.

**Comment by mattijn** [comment]
I'm happy this issue is resolved. Its fun to play with this.

```python
import topojson as tp
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
tp.Topology(data=world).toposimplify(4).topoquantize(20).to_alt(color='properties.name:N')
```
<img width="519" alt="image" src="https://user-images.githubusercontent.com/5186265/101981324-482d6080-3c6c-11eb-8b6c-f67dfdf3f1cf.png">

**Comment by ljwolf** [comment]
If you're game for a numba implementation, I'm sure that'd help accelerate things? I prefer working on the topojson-style data structure, and numba could work well with ragged arrays stored as lists of tuples.

**Comment by mattijn** [comment]
This is discussed previously with @Casyfill and might be a good method indeed to improve speed further. It might be very simple to get good results, but I've never tried it. Let me open a new issue so it can be tracked.
