### ISSUE TITLE
Safe to assume order of objects.data.geometries?

### ISSUE THREAD

**Issue by dgilmanTORQATA** [mattijn/topojson#123]
I'd like to be able to add attributes and identifiers to the geometries that I feed into topojson. Right now the library doesn't make any attempt to preserve or push anything through.

However, it seems that the order of the `objects.data.geometries` list is the same order as the objects passed in, so I can mutate the final topojson output and put my properties in there. Is this output order the same as the input order, and is it safe to rely on in the interim before the topojson API gets extended to support my usecase?

**Comment by dgilmanTORQATA** [comment]
Alternatively, if you want to give some guidance on how you'd like it to to pipe forward attributes, or even just the id property on the geometry objects as that's all I really need, I can try writing a PR.

**Comment by mattijn** [comment]
Hi.
I would put attributes within the `properties` as per the definition of a Feature, see https://geojson.org.

Example:
```python
import topojson as tp
obj = tp.utils.example_data_africa()

# object prior entering topojson
obj0 = obj[0].copy()
del obj0['geometries'] #  all info except geometries
print(obj0)
```

> ```
> {'id': '1',
>  'type': 'GeometryCollection',
>  'properties': {'continent': 'Africa',
>   'gdp_md_est': 150600.0,
>   'iso_a3': 'TZA',
>   'name': 'Tanzania',
>   'pop_est': 53950935},
>  'bbox': (29.339997592900346,
>   -11.720938002166735,
>   40.31659000000002,
>   -0.9500000000000001)}
> ```
```python
# object after topojson
topo = tp.Topology(obj).to_dict()
after_obj0 = topo['objects']['data']['geometries'][0]
after_obj0
```

> ```
> {'id': '1',
>  'type': 'Polygon',
>  'properties': {'continent': 'Africa',
>   'gdp_md_est': 150600.0,
>   'iso_a3': 'TZA',
>   'name': 'Tanzania',
>   'pop_est': 53950935},
>  'bbox': (29.339997592900346,
>   -11.720938002166735,
>   40.31659000000002,
>   -0.9500000000000001),
>  'arcs': [[-6, 0, -84, -82, -77, -3, -100, -140, -137]]}
> ```
