### ISSUE TITLE
Specify type of supported geometries

### ISSUE THREAD

**Issue by kannes** [mattijn/topojson#19]
The readme says that "`dict` of geometries (`LineString`, `MultiLineString`, `Polygon`, `MultiPolygon`, `Point`, `MultiPoint`, `GeometryCollection`)" is supported but what kind of geometry objects are those? Shapely? Anything with [geo interface](https://gist.github.com/sgillies/2217756)?

**Comment by mattijn** [comment]
I would have said only shapely-like objects, but upon investigation it is any object that provide a `__geo_interface` since the packages uses the `shapely.geometry.shape` function to serialise the geometry of the objects.
