### ISSUE TITLE
tests failing, natural earth dataset changed 

### ISSUE THREAD

**Issue by mattijn** [mattijn/topojson#199]
[Tests are failing ](https://github.com/mattijn/topojson/actions/runs/3679331506/jobs/6223667017)as of https://github.com/geopandas/geopandas/pull/2670.
Decision to use an ever-changing administrative boundary dataset for many tests was probably not my smartest move.

**Comment by DanRunfola** [comment]
https://github.com/wmgeolab/geoBoundaries

Provides a global adm dataset, you could pick a commit to keep it static. I'm building a new version before the end of the year.

Global is here:https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/CGAZ

**Comment by mattijn** [comment]
Thanks for posting these links. Using a static version by means of a commit is a good idea! 

Will you support a low resolution adm dataset version as well?
The current test version of my global adm is not bigger than `300K`, where the smallest zip I could find on the global release page of CGAZ is `~100MB`
