### ISSUE TITLE
Specify structure of "dict of geometries"

### ISSUE THREAD

**Issue by kannes** [mattijn/topojson#20]
The readme says that "`dict` of geometries (`LineString`, `MultiLineString`, `Polygon`, `MultiPolygon`, `Point`, `MultiPoint`, `GeometryCollection`)" is supported but how should that `dict` be structured?

The example has random made-up keys with a geo interface like value. The keys then vanish in the topojson representation. Is there any need for specific keys?

**Comment by mattijn** [comment]
The dictionary structure with` {key : geom}` originate from initial development where was decided to build an architecture where the many available tests of topojson-server repository (eg. https://github.com/topojson/topojson-server/blob/master/test/join-test.js) could easily be re-used. 

So maybe there is no direct function of the keys in the derivation of the topoloy, the structure was very important to me to once I started writing this package.

I add a line in the README about the structure of the dict: https://github.com/mattijn/topojson#type-dict
