### ISSUE TITLE
Please support lists of geometries

### ISSUE THREAD

**Issue by kannes** [mattijn/topojson#21]
I have a list of geometries, not a dict. It would be great if that simple structure would be supported as well, especially considering the keys of a dict of geometries seem not used after all (re https://github.com/mattijn/topojson/issues/20)

**Comment by mattijn** [comment]
Good suggestion!

**Comment by kannes** [comment]
Thank you!

**Comment by mattijn** [comment]
Much welcome. Any other usage questions, bug reports or suggestions are much appreciated!
