### ISSUE TITLE
serialize_as_geojson outputs invalid GeoJSON

### ISSUE THREAD

**Issue by Zaczero** [mattijn/topojson#214]
I have noticed that geometry produced by serialize_as_geojson is not always valid. Essentially, a PostGIS server logged information like:

```txt
NOTICE:  Self-intersection at or near point -1.7646430670616482 43.343036981578791
NOTICE:  Self-intersection at or near point -56.757341551608846 -27.571978182790648
NOTICE:  Self-intersection at or near point -58.109818573194246 -33.009761116125937
NOTICE:  Self-intersection at or near point -56.792214220247686 -27.572121122268854
NOTICE:  Self-intersection at or near point 6.1868958925049995 50.640692266757227
NOTICE:  Self-intersection at or near point 6.1907987161590761 50.663999944400551
```

which made me investigate. I then confirmed the issue by checking:

```py
shape(wkt_string).is_valid
```

where `wkt_string` is:

[wkt.txt](https://github.com/mattijn/topojson/files/13675540/wkt.txt)

I am using the following configuration:

```py
tp.Topology(countries_geoms, prequantize=False)
topo.toposimplify(q, inplace=True)
features = serialize_as_geojson(topo.to_dict())['features']
```

**Comment by mattijn** [comment]
there is also a `validate` argument as option within `serialize_as_geojson(.., validate=True)`. See here what it is doing:

https://github.com/mattijn/topojson/blob/main/topojson/utils.py#L533

```python
geom = shape(geom_map).buffer(0)
```
