### ISSUE TITLE
Topojson >=1.6 requires Python >=3.8, but there is no guard against Python <3.8

### ISSUE THREAD

**Issue by DManowitz** [mattijn/topojson#215]
At the very least, in `topojson/ops.py`, there is an import from `importlib.metadata`.  This package is only present in Python >=3.8.  However, I was able to install this package in a Python 3.7 environment, and I got an exception because of this when I tried to import topojson.

There should be a `requires-python = ">=3.8"` statement added to the `pyproject.toml` file.

**Comment by mattijn** [comment]
Thanks for raising this issue! For reference, it's this line where is being referred to: https://github.com/mattijn/topojson/blob/main/topojson/ops.py#L34

**Comment by DManowitz** [comment]
@mattijn, yes, that's what caused the exception
