### ISSUE TITLE
LICENSE references sgillies

### ISSUE THREAD

**Issue by kannes** [mattijn/topojson#22]
LICENSE says

> Neither the name of Sean C. Gillies nor the names of

that should be yours ;)

Or just use the simpler form of the https://opensource.org/licenses/BSD-3-Clause where your name is just at the top.

**Comment by kannes** [comment]
Sorry for the tornado of issues btw. I am just evaluating the module for something and like to contribute feedback like this. Keep up the great work!

**Comment by mattijn** [comment]
Your issues and feedback are much appreciated! I will try to solve and close them one by one
