### ISSUE TITLE
add to_geojson() function

### ISSUE THREAD

**Issue by mattijn** [mattijn/topojson#68]
Similar to #67, it would be good to have a `to_geojson()` function available on the `Topology` object.

**Comment by kylepollina** [comment]
I created a python CLI for converting topojson to geojson. I honestly don't understand how it works, I just packaged some code I found online into a CLI for my own purposes. Here's a link for the source code, take a look at the to_geojson() function: https://github.com/kylepollina/topo2geo/blob/master/topo2geo/core.py#L98

**Comment by kylepollina** [comment]
I would create a PR but I don't have the time to figure out how your library works. Hope this helps!

**Comment by mattijn** [comment]
Thanks for your comments! Once I can prioritise some time, will also include your example script in the analysis to match the full feature request.

**Comment by mattijn** [comment]
Thanks again for the information you provided. This issue is now fixed by PR https://github.com/mattijn/topojson/pull/72. The main difference with the code you provided and the code ending up in the repo is the serialization of quantized arcs (I do it in once for all arcs using numpy) and I had to catch some non-trivial geometries like (nested) geometrycollections, points and multipoints.
