### ISSUE TITLE
bounding box not working when using geodata

### ISSUE THREAD

**Issue by Saravji** [mattijn/topojson#79]
I'm working on using your library including a warper to process postgres geogis data into TopoJson.
I'm getting a `"ValueError: not enough values to unpack (expected 4, got 0)"` error when calling `tj = topojson.Topology(geoList)`.
geoList content is enclosed as "pretty" and "raw" files
[geoList_pretty.txt](https://github.com/mattijn/topojson/files/4617905/geoList_pretty.txt)
[geoList_raw.txt](https://github.com/mattijn/topojson/files/4617907/geoList_raw.txt)

**Comment by mattijn** [comment]
Thanks for reporting the issue! 
Your data contain two elements that are both invalid geometric objects. The features are referenced as `MultiPolygon`, where they are of type `Polygon`.

Let me give an example with a minimal working example, where I use the `shapely.geometry.shape()` function to parse the feature.

First the `geom_bad`:
```python
import json
from shapely import geometry

geom_bad = {
    "type": "MultiPolygon",
    "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]
}
geometry.shape(geom_bad)
```

> ```bash
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-2-f1d0a64aaf34> in <module>
>       6     "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]
>       7 }
> ----> 8 geometry.shape(geom_bad)
> 
> ~/miniconda3/lib/python3.7/site-packages/shapely/geometry/geo.py in shape(context)
>      42         return MultiLineString(ob["coordinates"])
>      43     elif geom_type == "multipolygon":
> ---> 44         return MultiPolygon(ob["coordinates"], context_type='geojson')
>      45     elif geom_type == "geometrycollection":
>      46         geoms = [shape(g) for g in ob.get("geometries", [])]
> 
> ~/miniconda3/lib/python3.7/site-packages/shapely/geometry/multipolygon.py in __init__(self, polygons, context_type)
>      62             self._geom, self._ndim = geos_multipolygon_from_polygons(polygons)
>      63         elif context_type == 'geojson':
> ---> 64             self._geom, self._ndim = geos_multipolygon_from_py(polygons)
>      65 
>      66     def shape_factory(self, *args):
> 
> ~/miniconda3/lib/python3.7/site-packages/shapely/geometry/multipolygon.py in geos_multipolygon_from_py(ob)
>     136     assert L >= 1
>     137 
> --> 138     N = len(ob[0][0][0])
>     139     assert N == 2 or N == 3
>     140 
> 
> TypeError: object of type 'int' has no len()
> ```
And then the `geom_good` (same `coordinates`, different `type`):
```python
geom_good = {
    "type": "Polygon",
    "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]
}
geometry.shape(geom_good)
```
<img width="96" alt="image" src="https://user-images.githubusercontent.com/5186265/81744343-5f705980-94a3-11ea-886b-3fa1aa31ca48.png">

The `topojson.Topology()` function adopts some default parameter settings, among which `prequantize=True`. 

When setting this to `False` will not give the provided error when using two bad geometries in a list. It will return an empty Topology object stating that 2 invalid geometric objects were removed:
```python
geoms_bad = [
    {
        "type": "MultiPolygon",
        "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]
    },
    {
        "type": "MultiPolygon",
        "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]
    }
]

import topojson
topojson.Topology(geoms_bad, prequantize=False)
```

> ```bash
> WARNING:root:removed 2 invalid geometric objects
> Topology(
> {'arcs': [],
>  'bbox': [],
>  'coordinates': [],
>  'objects': {'data': {'geometries': [], 'type': 'GeometryCollection'}},
>  'type': 'Topology'}
> )
> ```

The `prequantize=True` is activated in the `Join` class and there is your reported error raised:
```python
from topojson.core.join import Join
Join(geoms_bad, options={'prequantize': True})
```

> ```bash
> WARNING:root:removed 2 invalid geometric objects
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-7-8ecb9e9e8f83> in <module>
>       1 from topojson.core.join import Join
> ----> 2 Join(geoms_bad, options={'prequantize': True})
> 
> ~/topojson/topojson/core/join.py in __init__(self, data, options)
>      59 
>      60         # execute main function
> ---> 61         self.output = self.joiner(self.output)
>      62 
>      63     def __repr__(self):
> 
> ~/topojson/topojson/core/join.py in joiner(self, data)
>     154 
>     155             data["linestrings"], data["transform"] = quantize(
> --> 156                 data["linestrings"], data["bbox"], quant_factor
>     157             )
>     158 
> 
> ~/topojson/topojson/ops.py in quantize(linestrings, bbox, quant_factor)
>     475     """
>     476 
> --> 477     x0, y0, x1, y1 = bbox
>     478     try:
>     479         kx = 1 / ((quant_factor - 1) / (x1 - x0))
> 
> ValueError: not enough values to unpack (expected 4, got 0)
> ```

Maybe [this](https://github.com/mattijn/topojson/blob/master/topojson/core/join.py#L163:L165) `if` statement and indented statement block should be placed [there](https://github.com/mattijn/topojson/blob/master/topojson/core/join.py#L146).

Again, thanks for the bug report! The main culprit is feeding invalid geometric objects to the Topology function. If you set the `prequantize` parameter to `False` you are fine for now (or, maybe even better, fix the invalid geometries) 

But the Topology function should not raise this type of error. I think I know where to fix it, but that will do later.
