### ISSUE TITLE
Non-topological simplification

### ISSUE THREAD

**Issue by DanRunfola** [mattijn/topojson#84]
First and foremost, thank you for the effort you're putting into this package - much appreciated.

I was wondering what the rationale was for precluding the user from using a simplification algorithm that preserves topology - i.e., on this line:

https://github.com/mattijn/topojson/blob/fd271849921651f74e6a5c9f31481a310d334a52/topojson/ops.py#L569

Right now, it's hard-coded to use the DP algorithm (which does not preserve topology), rather than the shapely default (which does preserve topology).

I'm doing a quick pull of this later today to test what happens as well :)

**Comment by DanRunfola** [comment]
Ok - so, a very (very) brief test I just ran does work - i.e., simply changing preserve_topology=True doesn't bring everything crashing down.  I didn't run any additional tests beyond a quick Egypt case, using a very large toposimplify value (.01) which would have resulted in invalid polygons (with less than 3 points) if preserve_topolgy was set to False:

![image](https://user-images.githubusercontent.com/7882645/82469655-53336000-9a92-11ea-9e70-63ae6324db64.png)

**Comment by DanRunfola** [comment]
And toposimplify .1 - you can see it's working here.  If you have the preserve_topology = False for this particular configuration, it does result in invalid polygons as well.

![image](https://user-images.githubusercontent.com/7882645/82470151-f7b5a200-9a92-11ea-8846-619ad8f9601c.png)

**Comment by DanRunfola** [comment]
Full code for replication:
`import json
import requests
import subprocess
import topojson
import geojson
import topo2geo
from sys import getsizeof
from geojson import Feature, Point, FeatureCollection, Polygon
  
  
r = requests.get("https://www.geoboundaries.org/gbRequest.html?ISO=EGY&ADM=ADM1&VER=3_0_0")
	
#Zipfile URL:
dlPath = r.json()[0]['downloadURL']
	
#You can swap .zip for .geojson for direct access to the geometry.
#Alternatively, you can skip this, download the *.zip, extract it locally,
#then load in the shape file.
dlPath = dlPath.replace("-all.zip", ".geojson")
geoBoundary = requests.get(dlPath).json()


with open('topoTester.topo', 'w') as outfile:
  topo = topojson.Topology(FeatureCollection(geoBoundary['features']), 
                  prequantize=False,
                  presimplify=False,
                  toposimplify=.1, 
                  simplify_with='shapely', 
                  simplify_algorithm='dp', 
                  winding_order='CW_CCW').to_json()
  json.dump(json.loads(topo), outfile)
  
runstr = "python /home/cdsw/topo2geojson.py " + "topoTester.topo" + " output_geoTest.json"
subprocess.check_call(runstr, shell=True)

from matplotlib import pyplot as plt
from shapely.geometry import shape


with open('output_geoTest.json') as json_file:
  simplegeoBoundary = json.load(json_file)
  
#Matplotlib Visualization
fig = plt.figure(1, figsize=(10,5), dpi=300)
axs = fig.add_subplot(121)

mbpost = round(getsizeof(str(simplegeoBoundary)) / 1000000,2)

axs.set_title('Post Simplification ' + str(mbpost) + "MB")
	
#Accounting for Multipolygon Boundaries
for boundary in simplegeoBoundary["features"]:
  if(boundary["geometry"]['type'] == "MultiPolygon"):
    polys = list(shape(boundary["geometry"]))
    for poly in polys:
      xs, ys = poly.exterior.xy    
      axs.fill(xs, ys, alpha=0.5, fc='red', ec='black')
  else:
    xs, ys = shape(boundary["geometry"]).exterior.xy    
    axs.fill(xs, ys, alpha=0.5, fc='red', ec='black')

axs = fig.add_subplot(122)

mbpre = round(getsizeof(str(geoBoundary)) / 1000000,2)

axs.set_title('Original '  + str(mbpre) + "MB")
	
#Accounting for Multipolygon Boundaries
for boundary in geoBoundary["features"]:
  if(boundary["geometry"]['type'] == "MultiPolygon"):
    polys = list(shape(boundary["geometry"]))
    for poly in polys:
      xs, ys = poly.exterior.xy    
      axs.fill(xs, ys, alpha=0.5, fc='red', ec='black')
  else:
    xs, ys = shape(boundary["geometry"]).exterior.xy    
    axs.fill(xs, ys, alpha=0.5, fc='red', ec='black')

fig.savefig("example.png")`

**Comment by mattijn** [comment]
Thanks for the clear described issue. All good points here. This type of parameter setting for simplification should be included.

**Comment by DanRunfola** [comment]
Did a quick PR:
https://github.com/mattijn/topojson/pull/85

**Comment by mattijn** [comment]
I have introduced this option in #86 using the new introduced parameter `prevent_oversimplify`. Set to `True` for the so-called, topology-preserving variant of linestring simplification.
