### ISSUE TITLE
Creating topology from list of dicts does not always work without geojson installed

### ISSUE THREAD

**Issue by terencehonles** [mattijn/topojson#99]
I was surprised when trying the following:

prerequisites (notice no `geojson`)
```bash
pip install fiona topojson
```

```python
import fiona
import topojson

# shape files downloaded and unzipped from
# http://www.naturalearthdata.com/downloads/110m-cultural-vectors/
with fiona.open('ne_110m_admin_0_countries.shp') as f:
  topology = topojson.Topology(list(f))
```

What I expected was the topology would be loaded correctly, but instead I received:

```
WARNING:root:removed 177 invalid geometric objects
```

I looked into the source code / stepped through with the debugger and the issue is this path needs `geojson` to function, but there's no indication that was the problem

https://github.com/mattijn/topojson/blob/09d04774e23dbf39a2e807fe72141a30e95b9612/topojson/core/extract.py#L613-L615

I'm also a little surprised that the `dict` would be converted to a string and then loaded via `GeoJSON` I think calling `geojson.GeoJSON.to_instance(self._obj)` should be sufficient, but this doesn't remove this libraries dependency on `geojson` though. I'm not too familiar with the geojson/GIS space, but I think this library should probably require geojson in its dependencies or at *least* loudly complain if a user is trying to use a feature that requires `geojson`.

**Comment by mattijn** [comment]
Thanks for raising the issue! Fiona has no yet a `__geo_interface__` (https://github.com/Toblerity/Fiona/issues/785). 

But direct support of `fiona` features is worthwhile having! 

Thanks for the clear rapport and you are completely right about the confusion related to `geojson` while not being a dependency. That should not happen. Thanks for raising!

**Comment by mattijn** [comment]
This is fixed by https://github.com/mattijn/topojson/pull/100

**Comment by terencehonles** [comment]
I didn't get a chance to test, but look at the code it looks good. Thanks for making it more obvious what was happening!
